inherit_from: .rubocop_todo.yml
Rails:
  Enabled: true

# Line is too long を無視
Metrics/LineLength:
  Enabled: false

# Missing top-level class documentation comment. を無視
Style/Documentation:
  Enabled: false

# Use nested module/class definitions instead of compact style. を無視
Style/ClassAndModuleChildren:
  Enabled: false
